### ISSUE TITLE
Carousel animation for changing slides

### ISSUE THREAD

**Issue by amalitsky** [igordanchenko/yet-another-react-lightbox-lite#7]
### Is your feature request related to a problem? Please describe.

Currently, animation for slide changes is implemented with [View Transition API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) and it's basically fade-in & fade-out combination for picture to be removed and to appear.
I believe that's a native browser implementation without any customization by the library.

Would be cool to swap the opacity thing for a `translateX` animation. Kind of a regular carousel experience.

### Describe the solution you'd like

Personally, I think having an implementation of image carousel animation is the simplest solution, not requiring any API changes nor a lot of code being added to the library.

Alternative solution would be to make it customizable on the user's end. Which it partially is, due to being a native CSS technology. However there is catch with needing different animations on next vs previous transition (need to change direction of moving slides).

Also, could be solved on the user end, but the problem is that **current** slide needs to have appropriate (based on navigation request be the user) `view-transition-name` property _before_ `document.startViewTransition` call is made by the library. And that needs to be a different name, based on type of action: _next_ or _previous_.

Unfortunately `setIndex` is called within `document.startViewTransition` callback and it's too late to modify before-transition DOM state. And application consumer of the library knows how to modify it _only_ upon user click. Because `view-transition-name` needs to be set based on performed action: _next_ or _previous_.

So, solution for later problem could be having a `beforeIndexChange(index: number)` callback, so that consumer app has an opportunity to modify DOM **before** transition begins.

### Describe alternatives you've considered

SCSS part of the code of non-working solution, reliant on setting a class on Lightbox/Portal component based on `index` value received in `setIndex` and it's previous value.
```scss
.Lightbox {
  .yarll__carousel [role='group'] {
    contain: layout;
  }

  &_navigation {
    &_next {
      .yarll__carousel [role='group']:not([hidden]) {
        view-transition-name: lightbox-image-next;
      }
    }

    &_previous {
      .yarll__carousel [role='group']:not([hidden]) {
        view-transition-name: lightbox-image-previous;
      }
    }
  }

  ::view-transition-old(lightbox-image-next) {
    animation: 0.3s ease-out both next-move-out;
  }

  ::view-transition-new(lightbox-image-next) {
    animation: 0.3s ease-out both next-move-in;
  }

  ::view-transition-old(lightbox-image-previous) {
    animation: 0.3s ease-in both previous-move-out;
  }

  ::view-transition-new(lightbox-image-previous) {
    animation: 0.3s ease-in both previous-move-in;
  }

  @keyframes next-move-out {
    from {
      transform: translateX(0%);
    }

    to {
      transform: translateX(-100%);
    }
  }

  @keyframes next-move-in {
    from {
      transform: translateX(100%);
    }

    to {
      transform: translateX(0%);
    }
  }

  @keyframes previous-move-out {
    from {
      transform: translateX(0%);
    }

    to {
      transform: translateX(100%);
    }
  }

  @keyframes previous-move-in {
    from {
      transform: translateX(-100%);
    }

    to {
      transform: translateX(0%);
    }
  }
}
```

This approach works on the _new_ (appearing) image as expected, but _old_ image is not accounted for, because before calling `setIndex` none of the `navigation_next` or `navigation_previous` modifier classes are set. They are being removed by `useEffect` after each transition to prevent even more jarring animation.

### Additional Considerations
Transitions for header/footer/controls probably need to be different from an _image_ transition. Default `opacity` one work just fine for those elements
